apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-party
    role: master
    tier: backend
  name: mongo-master-party
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-party
      role: master
      tier: backend
  template:
    metadata:
      labels:
        app: mongo-party
        role: master
        tier: backend
    spec:
      containers:
      - image: mongo:3-xenial
        name: mongo-master
        ports:
        - containerPort: 27017
