apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: mongo-party
    tier: backend
  name: mongo-party
spec:
  serviceName: mongopartysvc
  replicas: 3
  selector:
    matchLabels:
      app: mongo-party
      tier: backend
  template:
    metadata:
      labels:
        app: mongo-party
        tier: backend
    spec:
      containers:
      - image: mongo:4.0.9 
        name: mongo-party
        command:
          - mongod  
          - "--replSet"
          - rs0 
          - "--bind_ip"  
          - 0.0.0.0     
          - "--smallfiles"
          - "--noprealloc"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data
          mountPath: /data/db
  volumeClaimTemplates: 
  - metadata:
      name: data
      annotations: 
        volume.alpha.kubernetes.io/storage-class: default
    spec: 
      accessModes: [ "ReadWriteOnce" ]
      resources: 
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-party
    tier: backend
  name: mongopartysvc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo-quote
    tier: backend
  clusterIP: None
