apiVersion: v1
kind: Service
metadata:
  labels:
    app: party
    role: business
    tier: backend
  name: partysvc
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
    name: grpc-party
  selector:
    app: party
    role: business
    tier: backend