apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: party
    role: business
    tier: backend
  name: party
spec:
  replicas: 1
  selector:
    matchLabels:
      app: party
      role: business
      tier: backend
  template:
    metadata:
      labels:
        app: party
        role: business
        tier: backend
    spec:
      containers:
      - image: party:v1
        name: party
        ports:
        - containerPort: 50051